/* Static mock data model — deterministic fake numbers everywhere. */

export function hashStr(s: string): number {
  let x = 7
  for (let i = 0; i < s.length; i++) x = (x * 31 + s.charCodeAt(i)) >>> 0
  return x
}
export function rnd(seed: string, min: number, max: number): number {
  return min + ((hashStr(seed) % 10000) / 10000) * (max - min)
}
export function fmt(n: number): string {
  return Math.round(n).toLocaleString('en-US')
}

/* ---------- data sources ---------- */
export interface Source {
  id: string
  name: string
  desc: string
  api: string
}
export interface SourceGroup {
  id: string
  title: string
  sub: string
  badge?: string
  sessionInSub?: boolean
  sources: Source[]
}

const API = 'https://api.store.example/v1'

export const GROUPS: SourceGroup[] = [
  {
    id: 'catalog',
    title: 'Catalog & Product Data',
    sub: 'Signals derived from product attributes, inventory and editorial metadata.',
    sources: [
      { id: 'new-products', name: 'New products', desc: 'Products recently added to the catalog.', api: `${API}/catalog/new-products` },
      { id: 'low-stock', name: 'Almost out of stock', desc: 'Products with low remaining inventory.', api: `${API}/inventory/low-stock` },
      { id: 'back-in-stock', name: 'Back in stock', desc: 'Products recently made available again.', api: `${API}/inventory/back-in-stock` },
      { id: 'on-promotion', name: 'On promotion', desc: 'Products currently associated with an active promotion.', api: `${API}/catalog/promotions` },
      { id: 'award-winning', name: 'Award-winning products', desc: 'Products carrying an editorial or external award flag.', api: `${API}/catalog/award-winning` },
      { id: 'press-features', name: 'Featured in the press', desc: 'Products associated with recent press coverage.', api: `${API}/catalog/press-features` },
      { id: 'top-rated', name: 'Top-rated products', desc: 'Products with the strongest customer rating signals.', api: `${API}/catalog/top-rated` },
    ],
  },
  {
    id: 'market',
    title: 'Market & Site-wide Behavior',
    sub: 'Aggregated demand signals generated by customer behavior across the commerce platform. These signals are available for all visitors and are not based on the current user’s personal data.',
    badge: 'All visitors',
    sources: [
      { id: 'trending', name: 'Trending right now', desc: 'Products experiencing unusually strong current interest.', api: `${API}/trends/products` },
      { id: 'best-sellers', name: 'Best sellers', desc: 'Products generating the highest sales volume.', api: `${API}/performance/best-sellers` },
      { id: 'most-viewed', name: 'Most viewed', desc: 'Products generating the highest number of views.', api: `${API}/performance/most-viewed` },
      { id: 'most-atc', name: 'Most added to cart', desc: 'Products with the highest add-to-cart activity.', api: `${API}/performance/most-added-to-cart` },
      { id: 'recent-purchases', name: 'Recently purchased', desc: 'Products recently purchased across the website.', api: `${API}/performance/recent-purchases` },
    ],
  },
  {
    id: 'preferences',
    title: 'User Preferences',
    sub: 'Personal preference signals available when the customer is identified and personal data is available.',
    badge: 'Logged-in users',
    sources: [
      { id: 'affinities', name: 'Preferred brands & categories', desc: 'Brands and categories with the strongest affinity for this customer.', api: `${API}/users/{userId}/affinities` },
      { id: 'wishlist', name: 'Wishlist & favorites', desc: 'Products explicitly saved by the customer.', api: `${API}/users/{userId}/wishlist` },
      { id: 'personal-affinity', name: 'Personalized product affinity', desc: 'Products ranked according to the customer’s long-term preference profile.', api: `${API}/users/{userId}/recommendations` },
    ],
  },
  {
    id: 'commercial',
    title: 'Customer Commercial History',
    sub: 'Signals generated from the customer’s historical purchasing activity.',
    badge: 'Logged-in customers',
    sources: [
      { id: 'purchases', name: 'Previously purchased', desc: 'Products purchased by this customer.', api: `${API}/users/{userId}/purchases` },
      { id: 'replenishment', name: 'Buy again / replenishment', desc: 'Products the customer may reasonably need to purchase again.', api: `${API}/users/{userId}/replenishment` },
      { id: 'similar-purchases', name: 'Similar to previously purchased', desc: 'Products similar to products previously purchased by the customer.', api: `${API}/users/{userId}/similar-to-purchases` },
      { id: 'purchase-cross-sell', name: 'Complements previous purchases', desc: 'Products commonly purchased with products previously purchased by this customer.', api: `${API}/users/{userId}/purchase-cross-sell` },
    ],
  },
  {
    id: 'browsing',
    title: 'Current & Recent Browsing Activity',
    sub: 'Signals generated by the customer’s current or recent browsing activity.',
    sessionInSub: true,
    sources: [
      { id: 'recently-viewed', name: 'Recently viewed', desc: 'Products viewed during the relevant session window.', api: `${API}/session/recently-viewed` },
      { id: 'recent-searches', name: 'Recent search intent', desc: 'Products or categories inferred from recent searches.', api: `${API}/session/recent-searches` },
      { id: 'recent-categories', name: 'Recently browsed categories', desc: 'Categories recently explored by the visitor.', api: `${API}/session/recent-categories` },
      { id: 'cart', name: 'Already in your cart', desc: 'Products currently present in the customer’s cart.', api: `${API}/session/cart` },
      { id: 'cart-fbt', name: 'Often purchased with products already in your cart', desc: 'Frequently bought together recommendations based on cart contents.', api: `${API}/session/cart/frequently-bought-together` },
      { id: 'recent-view-fbt', name: 'Often purchased with the most recently viewed product', desc: 'Frequently bought together recommendations based on the most recently viewed product.', api: `${API}/session/recent-view/frequently-bought-together` },
      { id: 'recent-view-similar', name: 'Similar to the most recently viewed product', desc: 'Products similar to the most recently viewed product.', api: `${API}/session/recent-view/similar` },
    ],
  },
]

export const SOURCES: Source[] = GROUPS.flatMap((g) => g.sources)

/* ---------- merch blocks ---------- */
export interface Block {
  id: string
  name: string
  group: string
  placement: string
  liveSince: string
  pm: string
  tech: string
  owner: string
  wire: { kind: string; hl: [number, number]; fold?: boolean }
}

const PEOPLE = {
  pm: ['Maya Chen', 'Louis Fabre', 'Nadia Benali', 'Marc Aubert'],
  tech: ['Alex Rivera', 'Sarah Kaminsky', 'Théo Girard', 'Anna Kovacs'],
  owner: ['Sarah Klein', 'Olivier Petit', 'Rachel Cohen', 'Hugo Lambert'],
}

export const BLOCK_GROUPS = ['Homepage', 'Browsing', 'Product & Purchase Journey'] as const

export const BLOCKS: Block[] = [
  { id: 'hp-above-fold', name: 'HP Merch Block — above the fold', group: 'Homepage', placement: 'Homepage — first merchandising slot, fully visible above the fold.', liveSince: 'March 12, 2025', wire: { kind: 'hp', hl: [38, 20], fold: true }, pm: '', tech: '', owner: '' },
  { id: 'hp-below-hero', name: 'HP Merch Block — right below hero banner', group: 'Homepage', placement: 'Homepage — below hero banner.', liveSince: 'March 12, 2025', wire: { kind: 'hp-hero', hl: [86, 20], fold: true }, pm: '', tech: '', owner: '' },
  { id: 'hp-below-content', name: 'HP Merch Block — below content section', group: 'Homepage', placement: 'Homepage — after the editorial content section, mid-page.', liveSince: 'April 2, 2025', wire: { kind: 'hp-hero', hl: [132, 20], fold: true }, pm: '', tech: '', owner: '' },
  { id: 'hp-bottom', name: 'HP Merch Block — bottom of page', group: 'Homepage', placement: 'Homepage — last section before the footer.', liveSince: 'April 2, 2025', wire: { kind: 'hp-hero', hl: [168, 20], fold: true }, pm: '', tech: '', owner: '' },
  { id: 'category', name: 'Category Page Merch Block', group: 'Browsing', placement: 'Category landing page — between the category header and the sub-category tiles.', liveSince: 'May 6, 2025', wire: { kind: 'category', hl: [70, 20] }, pm: '', tech: '', owner: '' },
  { id: 'catalog', name: 'Catalog Page Merch Block — above product list', group: 'Browsing', placement: 'Catalog / product-list page — horizontal strip right above the filtered product grid.', liveSince: 'May 6, 2025', wire: { kind: 'catalog', hl: [64, 18] }, pm: '', tech: '', owner: '' },
  { id: 'search', name: 'Search Results Merch Block', group: 'Browsing', placement: 'Search results page — strip above the result grid.', liveSince: 'June 18, 2025', wire: { kind: 'catalog', hl: [64, 18] }, pm: '', tech: '', owner: '' },
  { id: 'pdp', name: 'Product Page Merch Block', group: 'Product & Purchase Journey', placement: 'Product detail page — recommendations below product information, above the reviews section.', liveSince: 'March 12, 2025', wire: { kind: 'product', hl: [128, 22] }, pm: '', tech: '', owner: '' },
  { id: 'cart', name: 'Cart Page Merch Block', group: 'Product & Purchase Journey', placement: 'Cart page — under the line items, above the checkout call to action.', liveSince: 'March 28, 2025', wire: { kind: 'cart', hl: [126, 22] }, pm: '', tech: '', owner: '' },
  { id: 'mini-cart', name: 'Mini-cart / Cart Drawer Merch Block', group: 'Product & Purchase Journey', placement: 'Mini-cart drawer — compact vertical module under the drawer line items.', liveSince: 'September 9, 2025', wire: { kind: 'drawer', hl: [118, 40] }, pm: '', tech: '', owner: '' },
  { id: 'account', name: 'Account Page Merch Block', group: 'Product & Purchase Journey', placement: 'My-account dashboard — right column, under the order status card.', liveSince: 'July 22, 2025', wire: { kind: 'account', hl: [96, 34] }, pm: '', tech: '', owner: '' },
  { id: 'wishlist-block', name: 'Wishlist Merch Block', group: 'Product & Purchase Journey', placement: 'Wishlist page — below the saved items list.', liveSince: 'October 14, 2025', wire: { kind: 'cart', hl: [126, 22] }, pm: '', tech: '', owner: '' },
  { id: 'confirmation', name: 'Order Confirmation Merch Block', group: 'Product & Purchase Journey', placement: 'Order confirmation page — under the order summary.', liveSince: 'October 14, 2025', wire: { kind: 'cart', hl: [126, 22] }, pm: '', tech: '', owner: '' },
]
BLOCKS.forEach((b, i) => {
  b.pm = PEOPLE.pm[i % 4]
  b.tech = PEOPLE.tech[(i + 1) % 4]
  b.owner = PEOPLE.owner[(i + 2) % 4]
})

/* ---------- default weights (percent, columns sum to 100) ---------- */
const BOOSTS: Record<string, number> = {
  'trending|hp-above-fold': 3, 'recently-viewed|hp-above-fold': 3, 'best-sellers|hp-above-fold': 2,
  'best-sellers|hp-below-hero': 3, 'new-products|hp-below-hero': 3,
  'on-promotion|hp-below-content': 2, 'press-features|hp-below-content': 2,
  'wishlist|hp-bottom': 2, 'replenishment|hp-bottom': 2,
  'on-promotion|category': 3, 'trending|category': 2,
  'top-rated|catalog': 2, 'best-sellers|catalog': 2,
  'recent-searches|search': 4, 'recently-viewed|search': 2,
  'recent-view-similar|pdp': 4, 'recent-view-fbt|pdp': 3, 'top-rated|pdp': 1,
  'cart-fbt|cart': 4, 'replenishment|cart': 2,
  'cart-fbt|mini-cart': 4,
  'replenishment|account': 4, 'purchases|account': 2, 'similar-purchases|account': 2,
  'back-in-stock|wishlist-block': 3, 'wishlist|wishlist-block': 0, 'similar-purchases|wishlist-block': 2,
  'purchase-cross-sell|confirmation': 3, 'replenishment|confirmation': 3,
}

export type Weights = Record<string, number>

export function defaultWeights(): Weights {
  const w: Weights = {}
  for (const b of BLOCKS) {
    const scored = SOURCES.map((s) => {
      const key = `${s.id}|${b.id}`
      const base = (hashStr(key) % 100) / 100
      const boost = BOOSTS[key] ?? 0
      return { key, score: base + boost }
    }).sort((a, z) => z.score - a.score)
    const chosen = scored.slice(0, 7)
    const total = chosen.reduce((acc, c) => acc + c.score, 0)
    const raw = chosen.map((c) => ({ key: c.key, exact: (c.score / total) * 100 }))
    let alloc = raw.map((r) => ({ key: r.key, v: Math.floor(r.exact), frac: r.exact - Math.floor(r.exact) }))
    let remainder = 100 - alloc.reduce((acc, a) => acc + a.v, 0)
    alloc = alloc.sort((a, z) => z.frac - a.frac)
    for (let i = 0; i < remainder; i++) alloc[i % alloc.length].v += 1
    for (const s of SOURCES) w[`${s.id}|${b.id}`] = 0
    for (const a of alloc) w[a.key] = a.v
  }
  return w
}

/* ---------- KPIs ---------- */
export const PERIODS = [
  { id: '24h', label: 'Past 24 hours', factor: 1 / 30 },
  { id: '30d', label: 'Past 30 rolling days', factor: 1 },
  { id: 'cmonth', label: 'Current calendar month', factor: 14 / 30 },
  { id: 'cyear', label: 'Current calendar year', factor: 7.47 },
  { id: '12m', label: 'Past rolling 12 months', factor: 12.17 },
] as const
export type PeriodId = (typeof PERIODS)[number]['id']

export interface Kpis {
  displayed: number
  viewed: number
  viewedDesktop: number
  viewedMobile: number
  clicked: number
  atc: number
}

function base30d(b: Block): Kpis {
  const displayed = rnd(b.id + 'D', 180_000, 1_400_000)
  const viewed = displayed * rnd(b.id + 'V', 0.45, 0.78)
  const deskShare = rnd(b.id + 'ds', 0.46, 0.66)
  const clicked = viewed * rnd(b.id + 'C', 0.02, 0.09)
  const atc = rnd(b.id + 'A', 8, 35)
  return { displayed, viewed, viewedDesktop: viewed * deskShare, viewedMobile: viewed * (1 - deskShare), clicked, atc }
}

export function kpisFor(b: Block, period: PeriodId): Kpis {
  const f = PERIODS.find((p) => p.id === period)!.factor
  const k = base30d(b)
  return {
    displayed: k.displayed * f,
    viewed: k.viewed * f,
    viewedDesktop: k.viewedDesktop * f,
    viewedMobile: k.viewedMobile * f,
    clicked: k.clicked * f,
    atc: Math.max(1, k.atc + rnd(b.id + period, -1.5, 1.5)),
  }
}

export function kpisLifetime(b: Block): Kpis {
  const months = rnd(b.id + 'life', 10, 17)
  const k = base30d(b)
  return {
    displayed: k.displayed * months,
    viewed: k.viewed * months,
    viewedDesktop: k.viewedDesktop * months,
    viewedMobile: k.viewedMobile * months,
    clicked: k.clicked * months,
    atc: k.atc,
  }
}

export function ranks(): Record<string, { engagement: number; atc: number }> {
  const eng = BLOCKS.map((b) => {
    const k = base30d(b)
    return { id: b.id, v: k.clicked / k.viewed }
  }).sort((a, z) => z.v - a.v)
  const perf = BLOCKS.map((b) => ({ id: b.id, v: base30d(b).atc })).sort((a, z) => z.v - a.v)
  const out: Record<string, { engagement: number; atc: number }> = {}
  for (const b of BLOCKS) {
    out[b.id] = {
      engagement: eng.findIndex((x) => x.id === b.id) + 1,
      atc: perf.findIndex((x) => x.id === b.id) + 1,
    }
  }
  return out
}

/* ---------- versions ---------- */
export type VersionStatus = 'draft' | 'live' | 'previously-live'
export interface ImpactEstimation {
  engagement: string
  atc: string
}
export interface ImpactAnalysis {
  engagement: { est: string; obs: string; variance: string }
  atc: { est: string; obs: string; variance: string }
}
export interface MixVersion {
  id: string
  name: string
  status: VersionStatus
  date: string
  by: string
  source: string | null
  desc: string
  estimation: ImpactEstimation | null
  analysis?: ImpactAnalysis
}

export const SEED_VERSIONS: MixVersion[] = [
  { id: 'V0.1', name: 'Initial skeleton', status: 'draft', date: 'May 4, 2026', by: 'Maya Chen', source: null, desc: 'First matrix draft — catalog and market signals only.', estimation: null },
  { id: 'V0.2', name: 'Session signals pass', status: 'draft', date: 'May 11, 2026', by: 'Maya Chen', source: 'V0.1', desc: 'Added browsing-activity signals and first weighting pass on the homepage blocks.', estimation: { engagement: '+1.4%', atc: '+0.9%' } },
  { id: 'V0.3', name: 'Cart rebalance', status: 'draft', date: 'May 21, 2026', by: 'Louis Fabre', source: 'V0.2', desc: 'Rebalanced cart and mini-cart around frequently-bought-together.', estimation: { engagement: '+2.1%', atc: '+1.7%' } },
  { id: 'V0.4', name: 'Launch candidate', status: 'draft', date: 'May 28, 2026', by: 'Maya Chen', source: 'V0.3', desc: 'Launch candidate: capped market signals, boosted replenishment on account.', estimation: { engagement: '+3.6%', atc: '+2.4%' } },
  { id: 'V1.0', name: 'First production mix', status: 'previously-live', date: 'June 2, 2026', by: 'Maya Chen', source: 'V0.4', desc: 'Published version created from V0.4. Configuration identical to V0.4 at publication.', estimation: { engagement: '+3.6%', atc: '+2.4%' }, analysis: { engagement: { est: '+3.6%', obs: '+3.1%', variance: '−0.5 pt' }, atc: { est: '+2.4%', obs: '+2.6%', variance: '+0.2 pt' } } },
  { id: 'V1.1', name: 'Search intent boost', status: 'draft', date: 'June 19, 2026', by: 'Nadia Benali', source: 'V1.0', desc: 'Raised recent search intent on the Search Results block.', estimation: { engagement: '+0.8%', atc: '+0.3%' } },
  { id: 'V1.2', name: 'Wishlist recovery', status: 'draft', date: 'July 1, 2026', by: 'Nadia Benali', source: 'V1.1', desc: 'Back-in-stock signal pushed on the Wishlist block.', estimation: { engagement: '+1.2%', atc: '+0.6%' } },
  { id: 'V1.3', name: 'Confirmation cross-sell', status: 'draft', date: 'July 16, 2026', by: 'Louis Fabre', source: 'V1.2', desc: 'Purchase cross-sell weighting on Order Confirmation.', estimation: null },
  { id: 'V1.4', name: 'Increase behavioral personalization on PDP', status: 'draft', date: 'August 3, 2026', by: 'Maya Chen', source: 'V1.3', desc: 'Higher weighting for recently viewed and user affinity signals.', estimation: { engagement: '+4.2%', atc: '+2.8%' } },
  { id: 'V2.0', name: 'PDP personalization increase', status: 'live', date: 'August 12, 2026', by: 'Maya Chen', source: 'V1.4', desc: 'Published version created from V1.4. Configuration identical to V1.4 at publication.', estimation: { engagement: '+4.2%', atc: '+2.8%' }, analysis: { engagement: { est: '+4.2%', obs: '+3.8%', variance: '−0.4 pt' }, atc: { est: '+2.8%', obs: '+3.1%', variance: '+0.3 pt' } } },
]

export function parseV(id: string): [number, number] {
  const m = id.match(/V(\d+)\.(\d+)/)
  return m ? [Number(m[1]), Number(m[2])] : [0, 0]
}

/* ---------- mix history per block ---------- */
export interface MixHistoryEntry {
  versionId: string
  versionName: string
  start: string
  end: string
  traffic: string
  status: 'Experiment rollout' | 'Full rollout' | 'Replaced'
}
export function mixHistory(b: Block): MixHistoryEntry[] {
  return [
    { versionId: 'V2.0', versionName: 'PDP personalization increase', start: 'Aug 12, 2026', end: 'Present', traffic: '100%', status: 'Full rollout' },
    { versionId: 'V1.0', versionName: 'First production mix', start: 'Jun 21, 2026', end: 'Aug 11, 2026', traffic: '100%', status: 'Replaced' },
    { versionId: 'V1.0', versionName: 'First production mix', start: 'Jun 2, 2026', end: 'Jun 20, 2026', traffic: '10%', status: 'Replaced' },
  ]
}
