import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useStore } from '../store'
import { Button, ExternalLink } from '../components/ui'
import { statusBadge } from './VersionsPage'

export function VersionDetailPage() {
  const { versionId } = useParams()
  const { versions, runEstimation } = useStore()
  const [running, setRunning] = useState(false)
  const v = versions.find((x) => x.id === versionId)

  if (!v) {
    return (
      <div className="px-8 py-8">
        <p className="text-sm text-neutral-500">Unknown version “{versionId}”.</p>
        <Link to="/versions" className="text-sm text-teal-700 underline underline-offset-2">Back to Version History</Link>
      </div>
    )
  }

  const isPublished = v.id.endsWith('.0')

  function handleRun() {
    setRunning(true)
    setTimeout(() => { runEstimation(v!.id); setRunning(false) }, 900)
  }

  return (
    <div className="max-w-4xl px-8 py-8">
      <Link to="/versions" className="text-xs text-neutral-400 underline underline-offset-2 hover:text-teal-700">← Version History</Link>
      <div className="mt-2 flex flex-wrap items-center gap-3">
        <h1 className="text-2xl font-semibold tracking-tight text-neutral-900">{v.id}</h1>
        {statusBadge(v.status)}
      </div>
      <p className="mt-0.5 text-[15px] font-medium text-neutral-700">{v.name}</p>

      <dl className="mt-5 divide-y divide-neutral-100 rounded-md border border-neutral-200 bg-white text-sm">
        <div className="flex justify-between px-4 py-2.5"><dt className="text-neutral-500">Created</dt><dd className="font-medium">{v.date}</dd></div>
        <div className="flex justify-between px-4 py-2.5"><dt className="text-neutral-500">Created by</dt><dd className="font-medium">{v.by}</dd></div>
        <div className="flex justify-between px-4 py-2.5"><dt className="text-neutral-500">Created from</dt>
          <dd className="font-medium">{v.source ? <Link to={`/versions/${v.source}`} className="text-teal-700 hover:underline">{v.source}</Link> : '—'}</dd></div>
        <div className="flex justify-between gap-8 px-4 py-2.5"><dt className="shrink-0 text-neutral-500">Description</dt><dd className="text-right text-neutral-700">{v.desc}</dd></div>
      </dl>

      <h2 className="mt-8 text-[13px] font-semibold uppercase tracking-wide text-neutral-500">Impact Estimation</h2>
      <p className="mt-1 text-xs text-neutral-400">Pre-launch projection performed by an external system — this SaaS only integrates the results.</p>
      <div className="mt-3 rounded-md border border-neutral-200 bg-white p-4">
        {v.estimation ? (
          <>
            <p className="text-sm font-medium text-teal-800">Impact Estimation completed</p>
            <div className="mt-3 flex flex-wrap gap-3">
              <div className="rounded-md border border-teal-200 bg-teal-50 px-4 py-2">
                <div className="text-lg font-semibold tabular-nums text-teal-800">{v.estimation.engagement}</div>
                <div className="text-[11px] text-teal-700">Estimated engagement impact</div>
              </div>
              <div className="rounded-md border border-teal-200 bg-teal-50 px-4 py-2">
                <div className="text-lg font-semibold tabular-nums text-teal-800">{v.estimation.atc}</div>
                <div className="text-[11px] text-teal-700">Estimated add-to-cart impact</div>
              </div>
            </div>
            <div className="mt-3">
              <ExternalLink href={`https://impact-suite.example.com/estimate?mix=${v.id}`}>Open full Impact Estimation</ExternalLink>
            </div>
          </>
        ) : (
          <>
            <p className="text-sm text-neutral-500">Impact Estimation: <b className="text-neutral-700">Not run</b></p>
            <div className="mt-3">
              <Button variant="primary" onClick={handleRun} disabled={running}>
                {running ? 'Running estimation…' : 'Run Impact Estimation'}
              </Button>
            </div>
          </>
        )}
      </div>

      {isPublished && (
        <>
          <h2 className="mt-8 text-[13px] font-semibold uppercase tracking-wide text-neutral-500">Impact Analysis</h2>
          <p className="mt-1 text-xs text-neutral-400">Comparison of the pre-launch Impact Estimation against the post-launch Impact Analysis. The post-launch analysis is also generated by an external tool.</p>
          <div className="mt-3 overflow-x-auto rounded-md border border-neutral-200 bg-white">
            {v.analysis ? (
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-neutral-200 text-left text-[11px] uppercase tracking-wide text-neutral-400">
                    <th className="px-4 py-2 font-medium">Metric</th>
                    <th className="px-4 py-2 text-right font-medium">Estimated pre-launch</th>
                    <th className="px-4 py-2 text-right font-medium">Observed post-launch</th>
                    <th className="px-4 py-2 text-right font-medium">Variance</th>
                  </tr>
                </thead>
                <tbody className="tabular-nums">
                  <tr className="border-b border-neutral-100">
                    <td className="px-4 py-2.5 font-medium">Engagement</td>
                    <td className="px-4 py-2.5 text-right">{v.analysis.engagement.est}</td>
                    <td className="px-4 py-2.5 text-right">{v.analysis.engagement.obs}</td>
                    <td className="px-4 py-2.5 text-right font-semibold">{v.analysis.engagement.variance}</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2.5 font-medium">Add to cart</td>
                    <td className="px-4 py-2.5 text-right">{v.analysis.atc.est}</td>
                    <td className="px-4 py-2.5 text-right">{v.analysis.atc.obs}</td>
                    <td className="px-4 py-2.5 text-right font-semibold">{v.analysis.atc.variance}</td>
                  </tr>
                </tbody>
              </table>
            ) : (
              <p className="px-4 py-3 text-sm text-neutral-500">Post-launch Impact Analysis: <b className="text-neutral-700">pending</b> — the post-launch observation window is still open.</p>
            )}
          </div>
          <div className="mt-3 flex gap-6">
            <ExternalLink href={`https://impact-suite.example.com/estimate?mix=${v.id}`}>Open Impact Estimation</ExternalLink>
            <ExternalLink href={`https://impact-suite.example.com/analysis?mix=${v.id}`}>Open Post-launch Impact Analysis</ExternalLink>
          </div>
        </>
      )}
    </div>
  )
}
